const DATA_PATH="data/federal-human-trafficking-prosecutions.csv";
const $=s=>document.querySelector(s);
const stateFilter=$("#state-filter"),typeFilter=$("#type-filter"),statusFilter=$("#status-filter"),searchFilter=$("#search-filter"),casesBody=$("#cases-body"),loadingMessage=$("#loading-message"),errorMessage=$("#error-message"),emptyMessage=$("#empty-message");
let cases=[];
function parseCSV(text){const rows=[];let row=[],field="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){row.push(field);field="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field="";}else field+=c;}row.push(field);if(row.some(v=>v.trim()))rows.push(row);const headers=rows.shift().map(h=>h.trim());return rows.map(vals=>Object.fromEntries(headers.map((h,i)=>[h,(vals[i]||"").trim()])))}
function val(o,names){const k=names.find(n=>Object.prototype.hasOwnProperty.call(o,n));return k?o[k]:""}
function normalize(o){return{caseId:val(o,["Case ID","Case Id"]),date:val(o,["Date Announced","Date"]),state:val(o,["State"]),district:val(o,["Federal District","District"]),traffickingType:val(o,["Trafficking Type","Type"]),defendants:val(o,["Defendant(s)","Defendants","Defendant"]),status:val(o,["Case Status","Status"]),sourceUrl:val(o,["Source URL","URL","Source"]),charges:val(o,["Charges"]),industry:val(o,["Industry"]),notes:val(o,["Notes"]),leadAgency:val(o,["Lead Agency","Lead Agencies"])}}
function unique(a){return[...new Set(a.filter(Boolean))].sort((x,y)=>x.localeCompare(y))}
function fill(select,values){values.forEach(v=>{const o=document.createElement("option");o.value=o.textContent=v;select.append(o)})}
function fmtDate(s){if(!s)return"—";const d=new Date(`${s}T00:00:00`);return Number.isNaN(d.getTime())?s:new Intl.DateTimeFormat("en-US",{year:"numeric",month:"short",day:"numeric"}).format(d)}
function cell(t,c=""){const td=document.createElement("td");td.textContent=t||"—";td.className=c;return td}
function render(list){casesBody.replaceChildren();list.forEach(x=>{const tr=document.createElement("tr");tr.append(cell(x.caseId,"case-id"),cell(fmtDate(x.date)),cell([x.state,x.district].filter(Boolean).join(" · "),"case-location"),cell(x.traffickingType),cell(x.defendants),cell(x.status,"status-text"));const td=document.createElement("td");if(x.sourceUrl){const a=document.createElement("a");a.href=x.sourceUrl;a.target="_blank";a.rel="noopener noreferrer";a.className="source-link";a.textContent="Official source";td.append(a)}else td.textContent="—";tr.append(td);casesBody.append(tr)});emptyMessage.hidden=list.length!==0;$("#visible-count").textContent=list.length;$("#state-count").textContent=new Set(list.map(x=>x.state).filter(Boolean)).size;$("#sex-count").textContent=list.filter(x=>x.traffickingType.toLowerCase().includes("sex")).length;$("#labor-count").textContent=list.filter(x=>/labor|forced labor/i.test(x.traffickingType)).length}
function apply(){const q=searchFilter.value.trim().toLowerCase(),s=stateFilter.value,t=typeFilter.value,st=statusFilter.value;render(cases.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!s||x.state===s)&&(!t||x.traffickingType===t)&&(!st||x.status===st)))}
[stateFilter,typeFilter,statusFilter].forEach(x=>x.addEventListener("change",apply));searchFilter.addEventListener("input",apply);$("#clear-filters").addEventListener("click",()=>{searchFilter.value=stateFilter.value=typeFilter.value=statusFilter.value="";apply()});
(async()=>{try{const r=await fetch(DATA_PATH);if(!r.ok)throw new Error(r.status);cases=parseCSV(await r.text()).map(normalize).filter(x=>x.caseId);fill(stateFilter,unique(cases.map(x=>x.state)));fill(typeFilter,unique(cases.map(x=>x.traffickingType)));fill(statusFilter,unique(cases.map(x=>x.status)));loadingMessage.hidden=true;render(cases)}catch(e){loadingMessage.hidden=true;errorMessage.hidden=false;errorMessage.textContent=`The dataset could not be loaded. Confirm that ${DATA_PATH} exists and that the CSV headers match the spreadsheet.`;console.error(e)}})();
